### ISSUE TITLE
crt.sh hangs on every *.nl address or give 502

### ISSUE THREAD

**Issue by rkettelerij** [crtsh/ct_monitor#11]
I'd though crt.sh was completely down the past couple of weeks. But it seems only *.nl address don't resolve. Try entering something like: nu.nl, google.nl, rijksoverheid.nl. The search either keep hanging or returns a 502.

**Comment by gcleaves** [comment]
I think the issue with google.nl is the number of results. It works for me, but takes a long time to respond.

**Comment by robstradling** [comment]
I think @gcleaves is correct, so I'm closing this ticket.
