### ISSUE TITLE
Partial mirror and database size

### ISSUE THREAD

**Issue by pl4nty** [crtsh/ct_monitor#12]
Hi Rob, thanks for building this excellent service!

I've deployed a partial mirror at https://crt.tplant.com.au after seeing the frontend go down a few times, and wanting to learn a bit more about CT in general. I'd like to keep it online but don't have much storage. Would you mind sharing an approx size of the current crt.sh database? I have a single replica ingesting Chromium-trusted logs at the moment.

Source code is public for the [k8s infrastructure](https://github.com/pl4nty/lab-infra/tree/main/kubernetes/oke/crtsh) and [container images](https://github.com/pl4nty/containers) (I'll add GPL SPDX headers soon). I'm happy to send through PRs for these too if you'd like

**Comment by elreydetoda** [comment]
Very cool @pl4nty! I'm not really affiliated with the project, but I'm going to look at trying to do something similar (hopefully soon) and maybe use some of your work (if you don't mind).
I don't personally enjoy using k8s but I'll probably do like a docker-compose stack :grin:

**Comment by pl4nty** [comment]
@elreydetoda no worries, let me know if you find any bugs. my containers aren't versioned though, so make sure you use specific digests rather than `latest`.

I might deprecate `crtsh-postgres` for a [cnpg](https://cloudnative-pg.io/) base image in a few months. Not sure if that'd work with docker-compose. And make sure you have plenty of system resources - I had to disable ca_monitor after it kept running out of memory (>16GB)

**Comment by robstradling** [comment]
> Would you mind sharing an approx size of the current crt.sh database?

Hi @pl4nty.  You can get this information via crt.sh:5432...
```
> psql -h crt.sh -p 5432 -U guest -d certwatch -c "select pg_size_pretty(pg_database_size('certwatch'));"
┌────────────────┐
│ pg_size_pretty │
├────────────────┤
│ 23 TB          │
└────────────────┘
(1 row)

Time: 99.118 ms
```

When I run `df` on one of the front-end replicas I see the same...
```
# df -h /var/lib/postgresql/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb         30T   23T  5.4T  81% /var/lib/postgresql
```

**Comment by robstradling** [comment]
> I had to disable ca_monitor after it kept running out of memory (>16GB)

Same here, a month or two ago.  I haven't yet had time to investigate.

**Comment by robstradling** [comment]
> after seeing the frontend go down a few times

I just got back from a 2 week vacation to find that our Ops team had migrated the crt.sh:443 and crt.sh:5432 front-ends to use a much, much more performant storage array.  This seems to have resulted in HUGE improvements to query response times, load averages, etc!

If it means I get to have nice things...I'm wondering if I should go away more often :-D

**Comment by elreydetoda** [comment]
> This seems to have resulted in HUGE improvements to query response times, load averages, etc!

Wow, ya it seems so much faster now! 🥳

> If it means I get to have nice things...I'm wondering if I should go away more often :-D

Lol, well that's definitely one way to look at it 🤣 

glad things are running a lot smoother now and again thanks for all the work you and your team does @robstradling !

**Comment by pl4nty** [comment]
> HUGE improvements to query response times

Thanks @robstradling, that's great news! I've gone ahead and decommissioned the mirror, but I'll keep the containers updated in case anyone else is interested. The mirror was pretty stable when filtering ingest to the ccTLD I needed, and I learnt a ton about CT/go/postgres, but query performance was pretty poor on my weak CPUs. Thanks again for this project :)
