### ISSUE TITLE
crt.sh seems down since 2023-12-13 10:53

### ISSUE THREAD

**Issue by GoldsteinE** [crtsh/ct_monitor#14]
That’s the date of the last `get-sth` call for all currently monitored logs: https://crt.sh/monitored-logs

OCSP responders page seems to suggest that the Postgres database is corrupted: https://crt.sh/ocsp-responders

> xlog flush request 2AF57/1BD39410 is not satisfied --- flushed only to 2AF56/C0E52BE0
> writing block 1994390 of relation base/16386/27732752 PL/pgSQL function ocsp_responders(text,integer,text,text,text,text,text,text,text,text,text,text,text) line 474 at FOR over EXECUTE statement PL/pgSQL function web_apis(text,text[],text[]) line 1787 at assignment

**Comment by Kamillaova** [comment]
@robstradling

**Comment by robstradling** [comment]
See https://groups.google.com/g/crtsh/c/vmuEQq7xHgM/m/yYwXK0pCAgAJ

**Comment by clauverjat** [comment]
Hello Rob and happy new year

I really like crt.sh, it's a very useful tool. May I suggest adding a banner on your website to warn users of the issue? It's been a few weeks now, therefore I expect people will get confused when analyzing their results and not seeing the expected certificates. If the site was just off by a few days, this would be less of an issue since there is a delay before the insertion to the TLogs happens anyway ; but it's been more than a few days now. Not everybody has the habit of checking Github to look for this issue. 

Kindly

**Comment by robstradling** [comment]
Hi @clauverjat.  I agree that a message alerting users about the breakage could be helpful, but it would be a bit awkward to implement.  The crt.sh:443 webpages are generated by PL/pgSQL code running on the replica DBs, which as you know are currently in read-only mode; so I won't be able to update the PL/pgSQL code on the replica DBs until they're no longer in read-only mode, by which time there'll be no need to display a message!
Currently I'm expecting that we'll be able to restore the service to normal operating conditions before the end of this week.

**Comment by clauverjat** [comment]
Oh I thought it would be a lot simpler to implement, this is unfortunate... 
Is that even the case for the home page ? Just having a banner there would already be good. If even this page is generated, I guess we're out of luck. I had a quick look at the page and the only other option I could see would be to change one of the images  in the footer. For instance adding the warning at the right of the sectigo logo. But of course this is very very hacky. So not sure if it's worth the effort.
```html
  <DIV>
    <A href="https://sectigo.com/"><IMG src="/sectigo_s.png"></A>
    &nbsp;<A href="https://github.com/crtsh"><IMG src="/GitHub-Mark-32px.png"></A>
  </DIV>
```

Anyway thanks for considering it. Good luck with restoring normal operation (in the end that's the most important).

**Comment by clauverjat** [comment]
Hi @robstradling 

Looks like the crt.sh service is back to normal !

**Comment by robstradling** [comment]
Yes indeed!  See https://groups.google.com/g/crtsh/c/vmuEQq7xHgM/m/HqwvsIdHBgAJ
