### ISSUE TITLE
Decoding certificates from RSS XML

### ISSUE THREAD

**Issue by neilstuartcraig** [crtsh/ct_monitor#2]
Hi

I'm currently writing a CLI script/app which we'll probably use in monitoring. I'm querying the RSS output on crt.sh and can't see what the formatting is. I note that linebreaks are HTML encoded then SGML encoded but more than that, I can't tell. Are you able to detail how the certs are encoded in the RSS output please? I don't really want to be making hundreds of HTTP requests to download each cert from crt.sh/?d=xxxxx for obvious reasons :-)

Cheers

**Comment by robstradling** [comment]
Hi.  Your question led me to discover a bug.  The base64 certificate data in the RSS output is being truncated.  I suspect that, once I've fixed this, your script will magically start working!

**Comment by robstradling** [comment]
Fixed by https://github.com/crtsh/certwatch_db/commit/36cb701a4d6037bbd5ede4cab1aed9e5830ec8fc

**Comment by robstradling** [comment]
@neilstuartcraig Is your CLI script/app able to parse the RSS output now?

**Comment by neilstuartcraig** [comment]
Hi @robstradling 
Yep! That's fixed it, thanks very much. I had a scan through the code and thought it was truncating but i'm not super familiar with PG or C so wasn't confident enough to suggest it.

I don't suppose you have any docs you could point me to on how the CT log APIs work by any chance? Just keen to see how the underpinnings work.

Thanks again

**Comment by robstradling** [comment]
@neilstuartcraig The CT log APIs are defined in section 4 of https://tools.ietf.org/html/rfc6962
